Repository Edwinliby/Hacktoberfest2022, pull requests merged in 2022-10, with the labels that each got.

#2 Create travelingsalesman.c
  travelingsalesman.c
Labels: hacktoberfest-accepted

#4 Add some c codes
  Sum_of_number_using_recursion.cpp
  factorial_recursion.cpp
  indirect_recursion.cpp
  nested_recursion.cpp
  tower_of_hanoi_recursion.cpp
  tree_recursion.cpp
Labels: hacktoberfest-accepted

#6 added sorting algos in java
  bubbleSort.java
  heapSort.java
  insertionSort.java
  mergeSort.java
  quickSort.java
  selectionSort.java
Labels: hacktoberfest-accepted

#7 Dijkstra’s Algorithm – Shortest distance Java
  DijkstrasAlgorithm.java
Labels: hacktoberfest-accepted

#8 Fibonacci Sequence.c
  fibonacci_sequence.c
Labels: good first issue, hacktoberfest-accepted

#10 Create Merge-Sort.py
  Merge-Sort.py
Labels: hacktoberfest-accepted

#12 CALCULATOR UI & LEAP YEAR OR NOT PROGRAM
  CalculatorUI/CalculatorUI.xcodeproj/project.pbxproj
  CalculatorUI/CalculatorUI.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  CalculatorUI/CalculatorUI.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  CalculatorUI/CalculatorUI.xcodeproj/project.xcworkspace/xcuserdata/uwall666.xcuserdatad/UserInterfaceState.xcuserstate
  CalculatorUI/CalculatorUI.xcodeproj/xcuserdata/uwall666.xcuserdatad/xcschemes/xcschememanagement.plist
  CalculatorUI/CalculatorUI/Assets.xcassets/AccentColor.colorset/Contents.json
  CalculatorUI/CalculatorUI/Assets.xcassets/AppIcon.appiconset/Contents.json
  CalculatorUI/CalculatorUI/Assets.xcassets/Contents.json
  CalculatorUI/CalculatorUI/CalculatorUIApp.swift
  CalculatorUI/CalculatorUI/ContentView.swift
  CalculatorUI/CalculatorUI/Preview Content/Preview Assets.xcassets/Contents.json
  leapyear_or_not.cpp
Labels: hacktoberfest-accepted

#13 PalindromeNumbers
  palindromenumbers.c
Labels: hacktoberfest-accepted

#14 Added matrixMultiplication.c
  matrixMultiplication.c
Labels: hacktoberfest-accepted

#15 AVL tree algorithm in C
  AVL_trees.c
Labels: hacktoberfest-accepted

#16 Add Bubble Sort Golang
  Go/BubbleSort.go
Labels: hacktoberfest-accepted

#17 Added codechef problem solution
  code_chef.cpp
Labels: hacktoberfest-accepted

#18 Create Selection-Sort.cpp
  C++/Selection-Sort.cpp
Labels: hacktoberfest-accepted

#22 Added voice.py
  C/hospital2.c
  Python/voice.py
Labels: hacktoberfest-accepted

#21 added digital clock
  C/clock.c
Labels: hacktoberfest-accepted

#20 College management application in JAVA
  CollegeManagement.java
Labels: hacktoberfest-accepted

#19 Create Counting-Sort.cpp
  C++/Counting-Sort.cpp
Labels: hacktoberfest-accepted

#24 Added a file on polynomial operations using linked list.
  C/polynomials.c
Labels: hacktoberfest-accepted

#25 First Commit
  .DS_Store
  C++/num_conv.cpp
Labels: hacktoberfest-accepted

#23 Create Kadane's.cpp
  C++/Kadane's.cpp
Labels: hacktoberfest-accepted

#26 Create bubble_sort.cpp
  C++/bubble_sort.cpp
Labels: hacktoberfest-accepted

#27 First commit
  C/game_rock_paper_scissors.c
Labels: hacktoberfest-accepted

#30 InsertionSort Using Recursion in C++
  C++/insertionSort.cpp
Labels: hacktoberfest-accepted

#31 Added chess game
  Python/chess.py
Labels: hacktoberfest-accepted

#37 Added permutation code using recursion in cpp
  C++/permutations_recursion.cpp
  C++/permutations_recursion.exe
Labels: hacktoberfest-accepted

#39 Create Stack_Array.java
  JAVA/Stack_Array.java
Labels: hacktoberfest-accepted

#40 Create tictactoe.c
  tictactoe.c
Labels: hacktoberfest-accepted

#43 Create radix_sort.cpp
  C++/radix_sort.cpp
Labels: hacktoberfest-accepted

#44 Added a rotate array problem in c++
  C++/rotate_array.cpp
Labels: hacktoberfest-accepted

#45 hacktoberfest-2022
  C/double_linked_list.c
  double_linked_list.c
Labels: hacktoberfest-accepted

#46 Sort the given matrix
  C++/sort_the_matrix.cpp
Labels: hacktoberfest-accepted

#48 C program to right rotate the elements of an array
  C/array_rotation.c
Labels: hacktoberfest-accepted

#49 Rotate Matrix Clockwise in java
  JAVA/rotational_matrix.java
Labels: hacktoberfest-accepted

#50 Create Bucketsort.java
  JAVA/Bucketsort.java
Labels: hacktoberfest-accepted

#51 Create CycleSort.java
  JAVA/CycleSort.java
Labels: hacktoberfest-accepted

#52 Create RadixSort.java
  JAVA/RadixSort.java
Labels: hacktoberfest-accepted

#53 Create TimSort.java
  JAVA/TimSort.java
Labels: hacktoberfest-accepted

#54 Postfix to prefix conversion
  C++/Postfix_to_Prefix_Conversion.cpp
Labels: hacktoberfest-accepted

#55 Heap sort
  C++/cpp/Heap sort.cpp
Labels: hacktoberfest-accepted

#73 Added Sudoku Game
  Python/sudoko.py
Labels: hacktoberfest-accepted

#72 Create generate QR code
  Python/Generate_qr_code.py
Labels: hacktoberfest-accepted

#71 Prims Algo Implementation in Java
  JAVA/PrimsAlgo.java
Labels: hacktoberfest-accepted

#56 added quick Sort cpp code
  C++/QuickSort.cpp
  C++/binary_search.cpp
  C/Quicksort.c
Labels: hacktoberfest-accepted

#70 Create Comb sort
  C++/Comb sort
Labels: hacktoberfest-accepted

#69 Create DFS (Depth First Search) algorithm
  JAVA/DFS (Depth First Search) algorithm
Labels: hacktoberfest-accepted

#59 Clone an undirected graph
  C++/Clone an Undirected Graph.cpp
Labels: hacktoberfest-accepted

#57 Lowest Common Ancestor of BST added
  C++/Lowest_Common_Ancestor_BST.cpp
Labels: hacktoberfest-accepted

#60 Create pot.c
  C/pot.c
Labels: hacktoberfest-accepted

#64 Create Prim's algorithm
  C++/Prim's algorithm
Labels: hacktoberfest-accepted

#68 Create BFS algorithm
  JAVA/BFS algorithm
Labels: hacktoberfest-accepted

#74 Added tic-tac-toe game
  Python/tictactoe.py
Labels: hacktoberfest-accepted

#62 Create factorial.c
  C/factorial.c
Labels: hacktoberfest-accepted

#65 Create Kruskal's Algorithm
  C++/Kruskal's Algorithm
Labels: hacktoberfest-accepted

#58 Topological sorting
  C++/cpp/Topological Sorting.cpp
Labels: hacktoberfest-accepted

#61 Create recursiveFibo.c
  C/recursiveFibo.c
Labels: hacktoberfest-accepted

#63 added code to find all subsets of a given set
  C++/subsets.cpp
Labels: hacktoberfest-accepted

#75 added median of two sorted arrays cpp code
  C++/Median_of_two_sorted_arrays.cpp
Labels: hacktoberfest-accepted

#80 added bankers problem
  C/bankers.c
Labels: hacktoberfest-accepted

#79 Create Insertion of data in Max - Heap.c
  C/Insertion of data in Max - Heap.c
Labels: hacktoberfest-accepted

#82 Best-Fit program
  C/BestFit.c
Labels: hacktoberfest-accepted

#87 added producer-consumer problem
  C/RoundRobin.c
  C/producer_consumer.c
Labels: hacktoberfest-accepted

#88 added scan program
  C/scan.c
Labels: hacktoberfest-accepted

#85 Add JavaScript factorial
  JavaScript/factorial.js
  JavaScript/factorial.recursion.js
Labels: hacktoberfest-accepted

#83 Create Deletion of data in max-heap.c
  C/Deletion of data in max-heap.c
Labels: hacktoberfest-accepted

#84 Create first_last_occurence.cpp
  C++/first_last_occurence.cpp
Labels: hacktoberfest-accepted

#86 Added a new directory Data Structures Implementations and removed one corrupted file(quicksort.c) from C directory
  C/QuickSort.c
  C/Quicksort.c
  Data Structures Implementations/Cpp/FibonacciHeap.cpp
Labels: enhancement, hacktoberfest-accepted

#91 Create LinkedListCycleDetection.c
  C/linkedListCycleDetection.c
Labels: hacktoberfest-accepted

#90 Digit Recognizer
  Python/Digit Recogniser/Digit Recogniser.ipynb
  Python/Digit Recogniser/mnist submission.csv
Labels: hacktoberfest-accepted

#89 New-Python program added
  Python/Displaying multiplication table of entered number.py
Labels: hacktoberfest-accepted

#92 Heap_Sort.py
  Python/Heap_Sort.py
Labels: hacktoberfest-accepted

#99 hierarchical_inheritance
  C++/hierarchical_inheritance.cpp
Labels: hacktoberfest-accepted

#95 Auto Email via python Added
  Python/Auto_email.py
Labels: hacktoberfest-accepted

#93 Adding Dijkstra Algorithm
  C/Dijkstra_Algorithm.c
Labels: hacktoberfest-accepted

#98 temperature converter
  Python/temp.py
Labels: hacktoberfest-accepted

#96 Add files via upload
  C++/excel sheet column number.cpp
Labels: hacktoberfest-accepted

#94 Added Krushkal's Algo in Java
  JAVA/KrushkalAlogoritm.java
Labels: hacktoberfest-accepted

#81 Pragati
  C++/boundary_traversal_of_tree.cpp
  C++/diagonal_traversal_of_binary_tree.cpp
Labels: hacktoberfest-accepted

#100 Triangles
  C/triangle.c
Labels: hacktoberfest-accepted

#102 Calculator file added
  C/Calc2_1.c
Labels: hacktoberfest-accepted

#106 Cyclic Sort
  C++/Cyclic Sort
Labels: hacktoberfest-accepted

#104 Added Patterns.py in Python Folder
  Python/Patterns.py
Labels: hacktoberfest-accepted

#103 added qwiksortr
  Python/qwiksort.pyadded
Labels: hacktoberfest-accepted

#115 Create SumOfDigits.c
  C/SumOfDigits.c
Labels: hacktoberfest-accepted

#114 Hacktoberfest-2022
  C/BinaryInsertionSort.c
Labels: hacktoberfest-accepted

#116 Strassen's Matrix Algorithm
  C/StrassensMatrix_Algorithm.c
Labels: hacktoberfest-accepted

#113 Added Spiral Order traversal of 2D matrix in C++
  C++/spiral order traversal of 2d matrix.cpp
Labels: hacktoberfest-accepted

#111 Menu branch
  Menu Driven Programs/Area.c
  Menu Driven Programs/Calculator.c
Labels: hacktoberfest-accepted

#112 Short & Simple Project Using C
  C/sale.c
Labels: hacktoberfest-accepted

#107 Identical Trees
  C++/Identical Trees
Labels: hacktoberfest-accepted

#110 hacktoberfest-2022
  JAVA/Pigeonhole Sort
Labels: hacktoberfest-accepted

#108 Radix Sort Implementation in Python
  Python/RadixSort.py
Labels: hacktoberfest-accepted

#109 Added Codechef Problem Suspense String Solution
  C++/Suspense_String.cpp
Labels: hacktoberfest-accepted

#127 BinarySearch floor and ceiling in java
  JAVA/BinarySearchCeiling.java
  JAVA/BinarySearchFloor.java
Labels: hacktoberfest-accepted

#117 Recursive Binary Search Algorithm
  C/RecursiveBinarySearch.c
Labels: hacktoberfest-accepted

#118 booleanParenthesisDP added
  C++/booleanParenthesisDP.cpp
Labels: hacktoberfest-accepted

#119 Create alphabetTriangle.c
  C/alphabetTriangle.c
Labels: hacktoberfest-accepted

#120 Create Menu of operations.c
  C/Menu of operations.c
Labels: hacktoberfest-accepted

#124 Create Radix_sort_in_Python.py
  Python/Heap_Sort_in_python.py
  Python/Radix_sort_in_Python.py
Labels: hacktoberfest-accepted

#125 Added Decimal to Binary Code
  C++/DectoBin.cpp
Labels: hacktoberfest-accepted

#128 Added facebook landing page on html
  Facebook Landing page/3.jpg
  Facebook Landing page/4.jpg
  Facebook Landing page/Readme.md
  Facebook Landing page/Your Gift ♥️/wallpaper (1).jpg
  Facebook Landing page/Your Gift ♥️/wallpaper (1).png
  Facebook Landing page/Your Gift ♥️/wallpaper (1).webp
  Facebook Landing page/Your Gift ♥️/wallpaper (10).jpg
  Facebook Landing page/Your Gift ♥️/wallpaper (11).jpg
  Facebook Landing page/Your Gift ♥️/wallpaper (12).jpg
  Facebook Landing page/Your Gift ♥️/wallpaper (6).jpg
  Facebook Landing page/Your Gift ♥️/wallpaper (7).jpg
  Facebook Landing page/Your Gift ♥️/wallpaper (8).jpg
  Facebook Landing page/Your Gift ♥️/wallpaper (9).jpg
  Facebook Landing page/facebook 🔶/demo (1).png
  Facebook Landing page/facebook 🔶/demo (2).png
  Facebook Landing page/facebook 🔶/images/eve.jpg
  Facebook Landing page/facebook 🔶/images/facebook-logo.png
  Facebook Landing page/facebook 🔶/images/favicon.ico
  Facebook Landing page/facebook 🔶/images/game.png
  Facebook Landing page/facebook 🔶/images/game2.png
  Facebook Landing page/facebook 🔶/images/gg.png
  Facebook Landing page/facebook 🔶/images/gg2.png
  Facebook Landing page/facebook 🔶/images/gg3.png
  Facebook Landing page/facebook 🔶/images/group.jpg
  Facebook Landing page/facebook 🔶/images/instagram.png
  Facebook Landing page/facebook 🔶/images/like.png
  Facebook Landing page/facebook 🔶/images/love.png
  Facebook Landing page/facebook 🔶/images/messenger.png
  Facebook Landing page/facebook 🔶/images/pp.jpg
  Facebook Landing page/facebook 🔶/images/pp2.jpg
  Facebook Landing page/facebook 🔶/images/pp3.jpg
  Facebook Landing page/facebook 🔶/images/pp4.jpg
  Facebook Landing page/facebook 🔶/images/ss.jpg
  Facebook Landing page/facebook 🔶/images/ss2.jpg
  Facebook Landing page/facebook 🔶/images/ss3.jpg
  Facebook Landing page/facebook 🔶/images/ss4.jpg
  Facebook Landing page/facebook 🔶/images/us.png
  Facebook Landing page/facebook 🔶/images/us2.png
  Facebook Landing page/facebook 🔶/images/us3.png
  Facebook Landing page/facebook 🔶/images/us4.png
  Facebook Landing page/facebook 🔶/images/user.jpg
  Facebook Landing page/facebook 🔶/images/user2.jpg
  Facebook Landing page/facebook 🔶/images/user3.jpg
  Facebook Landing page/facebook 🔶/images/user4.jpg
  Facebook Landing page/facebook 🔶/index.html
  Facebook Landing page/facebook 🔶/style.css
Labels: enhancement, hacktoberfest-accepted

#131 Added largest palindrome program in Java
  JAVA/Largest_palindrome_product.java
Labels: hacktoberfest-accepted

#129 Hacktoberfest-2022
  C/CountingSort.c
  C/RadixSort.c
Labels: hacktoberfest-accepted

#130 Website Connectivity Checker
  Python/website_connectivity_checker.py
Labels: hacktoberfest-accepted

#132 Hacktoberfest-2022
  C/TowerOfHanoi.c
Labels: hacktoberfest-accepted

#135 Create Prim's Algorithm.cpp
  C++/Kruskal's Algorithm.cpp
  C++/Prim's Algorithm.cpp
  C++/binaryKnapsack.cpp
Labels: hacktoberfest-accepted

#136 TrappingRainWater.cpp
  C++/TrappingRainWater.cpp
Labels: hacktoberfest-accepted

#140 Create TimSort.py
  Python/TimSort.py
Labels: hacktoberfest-accepted

#143 scramble_String added
  C++/scramble_StringDP.cpp
Labels: hacktoberfest-accepted

#142 Create double_triangle.c
  C/double_triangle.c
Labels: hacktoberfest-accepted

#138 Create Program to implement Bucket sort in Java
  JAVA/Program to implement Bucket sort in Java
Labels: hacktoberfest-accepted

#141 Added a bsic c script on double linked list
  C/double_ll.c
Labels: hacktoberfest-accepted

#145 C program to find number of keywords in a given Text file !!
  C/To_find_keywords.c
  C/To_find_keywords.txt
Labels: hacktoberfest-accepted

#139 Added code to find prime factors
  C++/prime_factor.cpp
Labels: hacktoberfest-accepted

#137 counting_sort.c
  counting_sort.c
Labels: hacktoberfest-accepted

#146 Recursion Programs
  C++/Asnmt 6 - Recursion/12Factorial
  C++/Asnmt 6 - Recursion/12Factorial.cpp
  C++/Asnmt 6 - Recursion/12Factorial.exe
  C++/Asnmt 6 - Recursion/13Binary.cpp
  C++/Asnmt 6 - Recursion/13Binary.exe
  C++/Asnmt 6 - Recursion/14Octal.cpp
  C++/Asnmt 6 - Recursion/14Octal.exe
  C++/Asnmt 6 - Recursion/1N_NaturalNum
  C++/Asnmt 6 - Recursion/1N_NaturalNum.cpp
  C++/Asnmt 6 - Recursion/1N_NaturalNum.exe
  C++/Asnmt 6 - Recursion/2N_NaturalNum_Rev.cpp
  C++/Asnmt 6 - Recursion/2N_NaturalNum_Rev.exe
  C++/Asnmt 6 - Recursion/3Odd_Num.cpp
  C++/Asnmt 6 - Recursion/3Odd_Num.exe
  C++/Asnmt 6 - Recursion/4Odd_Num_Rev.cpp
  C++/Asnmt 6 - Recursion/4Odd_Num_Rev.exe
  C++/Asnmt 6 - Recursion/5Even_Num.cpp
  C++/Asnmt 6 - Recursion/5Even_Num.exe
  C++/Asnmt 6 - Recursion/6Even_Num_Rev.cpp
  C++/Asnmt 6 - Recursion/6Even_Num_Rev.exe
  C++/Asnmt 6 - Recursion/7Squares.cpp
  C++/Asnmt 6 - Recursion/7Squares.exe
  C++/Asnmt 6 - Recursion/8Sum_N_num.cpp
  C++/Asnmt 6 - Recursion/8Sum_N_num.exe
Labels: hacktoberfest-accepted

#147 Left View of Binary Tree
  JAVA/LeftView.java
Labels: hacktoberfest-accepted

#41 Hello!, Hacktoberfest 2022
  C/helloworld.c
  C/helloworld.exe
Labels: hacktoberfest-accepted

#185 Calender Python Project
  Python/Calender.py
Labels: hacktoberfest-accepted

#194 Create random_password_generator.py
  Python/random_password_generator.py
Labels: hacktoberfest-accepted

#285 Add simple calculator code
  Python/simpleCalculator.py
Labels: hacktoberfest-accepted

#280 Create rock_paper_scissors.py
  Python/rock_paper_scissors.py
Labels: hacktoberfest-accepted

#277 Junit5 usage and handson demo
  JAVA/JUnitMavenDemo/pom.xml
  JAVA/JUnitMavenDemo/src/test/java/com/lti/junit5/MavenDemoTest.java
  JAVA/JUnitMavenDemo/target/classes/META-INF/MANIFEST.MF
  JAVA/JUnitMavenDemo/target/classes/META-INF/maven/com.lti/JUnitMavenDemo/pom.properties
  JAVA/JUnitMavenDemo/target/classes/META-INF/maven/com.lti/JUnitMavenDemo/pom.xml
  JAVA/JUnitMavenDemo/target/test-classes/com/lti/junit5/MavenDemoTest.class
  JAVA/Junit5Demo/bin/FunctionalInterfaceDemo.class
  JAVA/Junit5Demo/bin/com/lti/bookstore/model/Book.class
  JAVA/Junit5Demo/bin/com/lti/bookstore/model/Colors.class
  JAVA/Junit5Demo/bin/com/lti/bookstore/service/BookService.class
  JAVA/Junit5Demo/bin/com/lti/calc/Calculator.class
  JAVA/Junit5Demo/bin/com/lti/calc/StringTest.class
  JAVA/Junit5Demo/bin/com/lti/junit5/FirstJUnit5Test.class
  JAVA/Junit5Demo/bin/com/lti/junit5/LifeCycleDemoTest.class
  JAVA/Junit5Demo/bin/com/lti/junit5/ParameterizedDemo.class
  JAVA/Junit5Demo/bin/com/lti/junit5/RepeatedTestDemo.class
  JAVA/Junit5Demo/src/FunctionalInterfaceDemo.java
  JAVA/Junit5Demo/src/com/lti/bookstore/model/Book.java
  JAVA/Junit5Demo/src/com/lti/bookstore/model/Colors.java
  JAVA/Junit5Demo/src/com/lti/bookstore/service/BookService.java
  JAVA/Junit5Demo/src/com/lti/calc/Calculator.java
  JAVA/Junit5Demo/src/com/lti/calc/StringTest.java
  JAVA/Junit5Demo/test.csv
  JAVA/Junit5Demo/test/com/lti/junit5/FirstJUnit5Test.java
  JAVA/Junit5Demo/test/com/lti/junit5/LifeCycleDemoTest.java
  JAVA/Junit5Demo/test/com/lti/junit5/ParameterizedDemo.java
  JAVA/Junit5Demo/test/com/lti/junit5/RepeatedTestDemo.java
Labels: hacktoberfest-accepted

#276 Create snake-water-gun.py
  Python/snake-water-gun.py
Labels: hacktoberfest-accepted

#273 Added Binary search using javascript
  JavaScript/binary.js
Labels: hacktoberfest-accepted

#283 redblack_tree
  C/redblack.c
Labels: hacktoberfest-accepted

#265 Create insertion_sort.py
  Python/insertion_sort.py
Labels: hacktoberfest-accepted

#264 Create BubbleSort.py
  Python/BubbleSort.py
Labels: hacktoberfest-accepted

#246 Create tower of hanabi
  tower of hanabi
Labels: hacktoberfest-accepted
